@extends('layouts.public')

@section('title', $project->title . ' - Portfolio')

@section('content')
<!-- Project Hero -->
<section class="project-hero">
    <div class="container">
        <span class="featured-badge">Featured Case Study</span>
        <h1 class="project-hero-title">
            {{ $project->title }}
            @if($project->client)
                <br><span class="highlight">for {{ $project->client }}</span>
            @endif
        </h1>
        <p class="project-hero-desc">{{ $project->description }}</p>
        
        <div class="project-hero-buttons">
            @if($project->live_url)
                <a href="{{ $project->live_url }}" target="_blank" class="btn btn-primary">
                    <i class="fas fa-external-link-alt"></i> Visit Live Site
                </a>
            @endif
            @if($project->code_url)
                <a href="{{ $project->code_url }}" target="_blank" class="btn btn-outline">
                    <i class="fas fa-code"></i> View Code
                </a>
            @endif
        </div>

        <div class="project-meta">
            <div class="meta-item">
                <div class="meta-label">Client</div>
                <div class="meta-value">{{ $project->client ?? 'Personal' }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Role</div>
                <div class="meta-value">{{ $project->role ?? 'Developer' }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Timeline</div>
                <div class="meta-value">{{ $project->timeline ?? 'Ongoing' }}</div>
            </div>
            <div class="meta-item">
                <div class="meta-label">Tools</div>
                <div class="meta-value">
                    @if($project->tools)
                        {{ implode(', ', array_slice($project->tools, 0, 3)) }}
                    @else
                        Various
                    @endif
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Project Content -->
<section class="project-content">
    <div class="container">
        @if($project->challenge)
            <div class="content-section">
                <h2>The Challenge</h2>
                <div class="challenge-content">
                    @php
                        $challenge = $project->challenge;
                        // Split by numbered pattern (1. 2. 3. etc)
                        $points = preg_split('/\d+\.\s/', $challenge, -1, PREG_SPLIT_NO_EMPTY);
                        $hasNumberedPoints = count($points) > 1;
                    @endphp
                    
                    @if($hasNumberedPoints)
                        <ul class="challenge-list">
                            @foreach($points as $point)
                                @if(trim($point))
                                    <li>{{ trim($point) }}</li>
                                @endif
                            @endforeach
                        </ul>
                    @else
                        <p>{{ $challenge }}</p>
                    @endif
                </div>
            </div>
        @endif

        <!-- Project Gallery -->
        <!-- Project Gallery Carousel -->
        <div class="project-gallery-carousel">
            <div class="carousel-container">
                <div class="carousel-track">
                    <!-- Thumbnail (Main Image) -->
                    @if($project->thumbnail)
                        <div class="carousel-slide">
                            <img src="{{ asset('storage/' . $project->thumbnail) }}" alt="{{ $project->title }} - Main">
                        </div>
                    @endif

                    <!-- Additional Images -->
                    @if($project->images && is_array($project->images))
                        @foreach($project->images as $image)
                            <div class="carousel-slide">
                                <img src="{{ asset('storage/' . $image) }}" alt="{{ $project->title }} - Image {{ $loop->iteration }}">
                            </div>
                        @endforeach
                    @endif
                </div>

                <button class="carousel-btn prev-btn" aria-label="Previous image">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <button class="carousel-btn next-btn" aria-label="Next image">
                    <i class="fas fa-chevron-right"></i>
                </button>

                <div class="carousel-indicators">
                    <!-- Indicators will be generated by JS -->
                </div>
            </div>
        </div>

        @if($project->solution)
            <div class="content-section">
                <h2>The Solution & Results</h2>
                <div class="solution-content">
                    @php
                        $solution = $project->solution;
                        // Split by numbered pattern (1. 2. 3. etc)
                        $points = preg_split('/\d+\.\s/', $solution, -1, PREG_SPLIT_NO_EMPTY);
                        $hasNumberedPoints = count($points) > 1;
                    @endphp
                    
                    @if($hasNumberedPoints)
                        <ul class="solution-list">
                            @foreach($points as $point)
                                @if(trim($point))
                                    <li>{{ trim($point) }}</li>
                                @endif
                            @endforeach
                        </ul>
                    @else
                        <p>{{ $solution }}</p>
                    @endif
                </div>

                @if($project->key_improvements)
                    <h3 style="margin-top: 32px; margin-bottom: 16px;">Key Improvements</h3>
                    <div class="improvements-grid">
                        @foreach($project->key_improvements as $improvement)
                            <div class="improvement-card">
                                <div class="improvement-icon">
                                    <i class="fas fa-chart-line"></i>
                                </div>
                                <div>
                                    <div class="improvement-value">{{ $improvement['label'] ?? '' }}</div>
                                    <div class="improvement-label">{{ $improvement['description'] ?? '' }}</div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                @endif
            </div>
        @endif
    </div>
</section>

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const track = document.querySelector('.carousel-track');
        const slides = Array.from(track.children);
        const nextButton = document.querySelector('.next-btn');
        const prevButton = document.querySelector('.prev-btn');
        const indicatorsContainer = document.querySelector('.carousel-indicators');
        
        // Return if no slides
        if (slides.length === 0) return;

        // Create indicators
        slides.forEach((_, index) => {
            const indicator = document.createElement('div');
            indicator.classList.add('indicator');
            if (index === 0) indicator.classList.add('active');
            indicator.addEventListener('click', () => {
                moveToSlide(index);
            });
            indicatorsContainer.appendChild(indicator);
        });

        const indicators = Array.from(document.querySelectorAll('.indicator'));
        let currentIndex = 0;

        function updateButtons() {
            // Optional: Hide buttons at ends, but infinite loop is better or just keep them
            // For now, let's just keep them always active for loop or stop at ends
            // Loop implementation:
            /*
            if (currentIndex === 0) {
                prevButton.style.opacity = '0.5';
                prevButton.style.cursor = 'not-allowed';
            } else {
                prevButton.style.opacity = '1';
                prevButton.style.cursor = 'pointer';
            }
            */
        }

        function moveToSlide(index) {
            // Handle bounds for loop
            if (index < 0) index = slides.length - 1;
            if (index >= slides.length) index = 0;

            const amountToMove = -100 * index;
            track.style.transform = `translateX(${amountToMove}%)`;
            
            currentIndex = index;

            // Update indicators
            indicators.forEach(ind => ind.classList.remove('active'));
            if (indicators[currentIndex]) {
                indicators[currentIndex].classList.add('active');
            }
        }

        nextButton.addEventListener('click', () => {
            moveToSlide(currentIndex + 1);
        });

        prevButton.addEventListener('click', () => {
            moveToSlide(currentIndex - 1);
        });
        
        // Keyboard navigation
        document.addEventListener('keydown', (e) => {
            if (e.key === 'ArrowLeft') moveToSlide(currentIndex - 1);
            if (e.key === 'ArrowRight') moveToSlide(currentIndex + 1);
        });
    });
</script>
@endpush

@endsection
